/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * @stc/types — Aggregate DTS entrypoint
 *
 * This file aggregates STCAPI Tier1 public types.
 * Recommended structure:
 * - each spec lives in its own *.d.ts
 * - index.d.ts references them (or is generated by build tooling)
 *
 * NOTE:
 * This is a logical aggregator. In real packaging you can:
 * - use `/// <reference path="./*.d.ts" />` for ambient namespaces, OR
 * - re-export modules (preferred if not using global namespaces).
 *
 * Current STCAPI specs are declared as `export declare namespace STC { ... }`,
 * so re-exporting is typically done by including files in `types` build output.
 */

/* ---------------------------------------------
 * Option A (ambient / reference-style bundling)
 * ---------------------------------------------
 * Uncomment if you bundle with reference paths:
 */

// /// <reference path="./collection.d.ts" />
// /// <reference path="./channel.d.ts" />
// /// <reference path="./policy.d.ts" />
// /// <reference path="./docs.d.ts" />
// /// <reference path="./storage.d.ts" />
// /// <reference path="./fs.d.ts" />
// /// <reference path="./diagnostics.d.ts" />
// /// <reference path="./transport.d.ts" />
// /// <reference path="./apiclient.d.ts" />
// /// <reference path="./apihost.d.ts" />
// /// <reference path="./runtime.d.ts" />
// /// <reference path="./workbench.d.ts" />

/* ---------------------------------------------
 * Option B (module export surface)
 * ---------------------------------------------
 * If you instead switch to module exports (recommended long-term),
 * each spec file should export its own types and you can re-export here.
 *
 * For now, we provide a minimal module surface that exports the STC namespace type.
 */

/** Top-level STC namespace (import type { STC } from "@stc/types"). */
export declare namespace STC {
  // This namespace is intentionally empty here.
  // It is augmented by the individual spec .d.ts files included in the build.
}

/**
 * Convenience type exports (optional).
 * These are aliases to make usage ergonomic without deep namespace paths.
 * You can add more over time as needed.
 */
export type STCCollection<T extends STC.Collection.AnyRecord, K extends STC.Collection.Key = STC.Collection.Key> =
  STC.Collection.Collection<T, K>;

export type STCChannel<T> = STC.Channel.Channel<T>;

export type STCChat = STC.Chat.Chat;

export type STCDiagnosticsSink = STC.Diagnostics.Sink;

export type STCRuntime = STC.Runtime.Runtime;

export type STCStorage = STC.Storage;

export type STCFS = STC.FS;

/**
 * Proposal: If you decide to avoid global namespaces,
 * you can migrate to explicit module exports like:
 *
 * export * as Collection from "./collection";
 * export * as Channel from "./channel";
 * ...
 *
 * But that requires rewriting the spec files to be module-based.
 */
